### ISSUE TITLE
Register doesn't work.

### ISSUE THREAD

**Issue by colarrbear** [KhunakornP/ku-polls#40]
<img width="582" alt="image" src="https://github.com/user-attachments/assets/22bf7dfb-1705-4560-9603-bbb9f7fd6b5c">

I tried registering using the username `test` and password `test`, and used this account to log in. However, I couldn't log in to the Polls. The account also doesn't appear in the Django administration.

**Comment by KhunakornP** [comment]
After some testing I have concluded that this is an issue that occurs when a user tries to register an invalid password/did not fill in the same password twice. The password "test" does not meet django's AUTH_PASSWORD_VALIDATORS criteria. Trying with a vaild password such as User:LunarReverie Password: butterflies123 works. I will close this issue once I add error messages to the registration page

**Comment by KhunakornP** [comment]
Fixed in peer review bugfix#42

**Comment by KhunakornP** [comment]
Note to future self: link the issues first before merging
